#!/bin/bash

############################################################################################
# This script prints out your battery level in percentage                                  #
# AUTHOR: Kevin Vece                                                                       #
#                                                                                          #
# Requirements: bc (calculator)                                                            #
# Tested on Ubuntu 12.04, Archlinux                                                        #
#                                                                                          #
# Usage: batstat [-b]                                                                      #
#                                                                                          #
# Options:                                                                                 #
# -b     show a banner of the battery percentage for each battery                          #
#        this option requires the banner program is installed from the svbanner package    #
#                                                                                          #
############################################################################################

# CHECK FOR BC CALCULATOR
bc_check=$(whereis bc | grep "/usr/bin")
if [ -z "$bc_check" ]; then
    echo "You do not have bc installed. Do you want to install? [y/n] "
    read ans
    ans=$(sed "s_[A-Za-z][^ ]*_\1_")
    if [ "$ans" == "y" -o "$ans" == "Y" ]; then
	system_type=$(uname -a)
	sys_tmp=$(echo $system_type | grep -i "Arch")
	if [ -z "$sys_tmp" ]; then
	    sudo pacman -S bc
	fi
    else
	exit 1
    fi
fi
    

# FIND NUMBER OF BATTERIES
battery_list=$(ls /sys/class/power_supply/ | grep -i "BAT")
num_batts=$(echo $battery_list | wc -l)

# LOOP THROUGH BATTERIES
while [ $num_batts -gt 0 ]; do

    line=$(echo $battery_list | tail -n $num_batts | head -n 1)
    
    # GET THE CURRENT BATTERY LEVEL
    battery_line=$(cat /sys/class/power_supply/$line/uevent | grep -i "ENERGY_NOW=")
    current_battery_level=$(echo $battery_line | sed "s_[^0-9]*__g")

    # GET THE MAXIMUM BATTERY LEVEL
    battery_line=$(cat /sys/class/power_supply/$line/uevent | grep -i "ENERGY_FULL=")
    max_battery_level=$(echo $battery_line | sed "s_[^0-9]*__g")

    # GET CHARGING STATUS
    charge_status=$(cat /sys/class/power_supply/$line/status)
    charge_status=$(echo $charge_status | sed -e "s_[A-Za-z][A-Za-z ]*:__g" -e "s_ __g")

    # PRINT OUT BATTERY PERCENTAGE AND CHARGING STATUS
    curr_times_100=$(echo $current_battery_level*100 | bc)
    battery_percent=$(echo $curr_times_100/$max_battery_level | bc)
    if [ "$1" == "-b" ]; then
	echo
	banner "$line $battery_percent%"
    fi
    echo "$line is at $battery_percent% and $charge_status"
    let num_batts=$num_batts-1

done 

echo
